env:
  game: 'SpaceInvaders-v0'
  stack_len: 1
  seed: 1314121
  solved_criteria: 4000
  q_threhold: 4000
  pomdp: True
  pomdp_type: 'flickering'  # flickering|delete_dim
  # pomdp_mask: [1, 0, 1, 0]  # this mask is chosen depended on the hiding dimensions and the observation shape of the env (i.e. 0)
  pomdp_prob: 0.8
  mode: 0

model:
  model_file: 'spaceinvader_drqncnn.pt'
  kernel_num: 16
  hidden_dim: 32
  enable_dueling: False
  dueling_type: 'avg'
  dtype: 'torch.float32'

memory:
  size: 1000
  max_episode_length: 0  # no limit

env_type: 'atari'
model_type: 'drqn_cnn'
memory_type: 'episodic'
agent_type: 'drqn'
mode: 'train'  # train|test
value_criteria: 'MSELoss'
optimizer: 'Adam'
train_visualize: False
retrain: True
solved_stop: True

random_eps: 10
drqn_n_step: 3
steps: 100000
learn_start: 4000
gamma: 0.99
# clip_grad: 1.0
lr: 0.0001
lr_decay: False
eps_start: 0.9
eps_decay: 70000
eps_end: 0.1
prog_freq: 1000
target_model_update: 0.05
batch_size: 16
train_interval: 1
log_window_size: 100
test_nepisodes: 1
log_step_interval: 100
log_episode_interval: 10
use_tensorboard: False
bootstrap_type: 'double_q'  # learn_q|target_q|double_q